name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ghv/ghv.csproj

    - name: Build
      run: dotnet build ghv/ghv.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ghv/ghv.csproj --configuration Release --no-build --output ./output

    - name: Create zip file
      run: |
        if [ $RUNNER_OS == 'Windows' ]; then
          Compress-Archive -Path ./output/* -DestinationPath ./ghv-${{ matrix.os }}.zip
        else
          zip -r ghv-${{ matrix.os }}.zip ./output
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghv-${{ matrix.os }}
        path: ghv-${{ matrix.os }}.zip
