name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ghv/ghv.csproj

    - name: Build
      run: dotnet build ghv/ghv.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ghv/ghv.csproj --configuration Release --no-build --output ./output

    - name: Create installer on Windows
      if: runner.os == 'Windows'
      run: |
        curl -o "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl" "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl"
        iscc installer/Windows.iss
        move installer/GitHubView-installer.exe output/GitHubView-installer.exe

    - name: Create installer on Linux
      if: runner.os == 'Linux'
      env:
        MAINTAINER_EMAIL: ${{ secrets.Maintainer_Email }}
      run: |
        # 安装 dpkg
        sudo apt-get update
        sudo apt-get install -y dpkg
        # 创建 DEBIAN 目录和控制文件
        mkdir -p output/DEBIAN
        echo 'Package: GitHubView' > output/DEBIAN/control
        echo 'Version: 1.0' >> output/DEBIAN/control
        echo 'Section: base' >> output/DEBIAN/control
        echo 'Priority: optional' >> output/DEBIAN/control
        echo 'Architecture: all' >> output/DEBIAN/control
        echo "Maintainer: 鸭鸭「カモ」 <${MAINTAINER_EMAIL}>" >> output/DEBIAN/control
        echo 'Description: GHV Application' >> output/DEBIAN/control
        # 生成安装包
        dpkg --build output ghv.deb
        mv ghv.deb output/ghv.deb

    - name: Create installer on macOS
      if: runner.os == 'macOS'
      run: |
        # 创建安装包
        pkgbuild --root ./output --identifier DuckStudio.GitHubView --version 1.0 --install-location /Applications --scripts ./output GitHubView.pkg
        mv GitHubView.pkg output/GitHubView.pkg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghv-${{ matrix.os }}
        path: ./output
